#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: first_user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh-authorized-keys:
  - your-key
- name: second_user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh-authorized-keys:
  - your-key
bootcmd:
  - [sh ,-xc, "uptime"]
  - [sh ,-xc, "echo bootcmd"]
runcmd:

# Register the new Runner to your Gitlab account
- >
  docker run --rm -v /srv/gitlab-runner/config:/etc/gitlab-runner gitlab/gitlab-runner register
  --non-interactive
  --executor "docker"
  --docker-image alpine:latest
  --url "https://common-tasks.gitlab.yandexcloud.net/ - example url"
  --registration-token "XXXXX"
  --description "docker-runner"
  --tag-list "docker,instance-pool,exoscale"
  --run-untagged="true"
  --locked="false"
  --access-level="not_protected"

# Run the Gitlab Runner demon
- >
  docker run -d --name gitlab-runner --restart always
  -v /srv/gitlab-runner/config:/etc/gitlab-runner
  -v /var/run/docker.sock:/var/run/docker.sock
  gitlab/gitlab-runner:latest

final_message: "The system is finally up, after $UPTIME seconds"